export const SET_IS_IN_ADMIN_AREA = "SET_IS_IN_ADMIN_AREA"
export const SET_TABLE_HEADERS_AND_BODY = "SET_TABLE_HEADERS_AND_BODY";
export const SET_SELECTED_COMPONENT = "SET_SELECTED_COMPONENT"
export const SET_PIE_CHART_DATA = "SET_PIE_CHART_DATA"
export const SET_LINE_CHART_DATA = "SET_LINE_CHART_DATA";
export const SET_USER_ROLE = "SET_USER_ROLE"