export const SET_IS_IN_ADMIN_AREA = "SET_IS_IN_ADMIN_AREA"
export const SET_TABLE_HEADERS_AND_BODY = "SET_TABLE_HEADERS_AND_BODY";
export const SET_PIE_CHART = "SET_PIE_CHART"
export const SET_LINE_CHART = "SET_LINE_CHART";
export const SET_USER_ROLE = "SET_USER_ROLE"
export const GET_USERS = "GET_USERS"