export const ENROLL_TO_COURSE = "ENROLL_TO_COURSE"
export const UNENROLL_FROM_COURSE = "UNENROLL_FROM_COURSE"
export const FILTER_COURSES = "FILTER_COURSES"
export const SEARCH_COURSE = "SEARCH_COURSE"